### ISSUE TITLE
Add an option for simple setups

### ISSUE THREAD

**Issue by dfr** [mekanix/egress-monitor#1]
I have been using this to mark outgoing interfaces consistently so that I can write portable pf.conf fragments for container networking. For simple setups where there is a single FIB and the same interface for v4 and v6, if would be nice if there was an option to simplify the group naming to just 'egress' similar to OpenBSD.

**Comment by mekanix** [comment]
I can implement shorter group by removing fib0 if only one fib exists, but I'm afraid v4/v6 has to stay. Imagine the situation where v4 and v6 egress is the same and having only "egress" is fine. But then for some reason, your v6 default route changes so that v4 and v6 egress differ. There is no way to tell PF "hey, when you say egress I will know if it's v4 or v6".

Anyway, I'll start with removing fib0 and let's see what else we can do.

**Comment by mekanix** [comment]
It's implemented now without "fib0". Can you compile it from git and let me know if it works for you, too?

**Comment by dfr** [comment]
I'm running with the latest from git and that simplifies things. On the subject of 'egress', perhaps the interface(s) could be put in two (or three) groups, v4egress if there is a v4 default route, v6egress if there is a v6 default route and egress if either default route exists. For my (admittedly very simple) use case, this ruleset should work even if v4 and v6 exit on different interfaces:
```
nat on egress inet from <cni-nat> to any -> (egress)
nat on egress inet6 from <cni-nat> to !ff00::/8 -> (egress)
table <cni-nat>
```
If v4 and v6 differ, the second rule will still only trigger on the v6 interface even though both are in the egress group. I'm not sure exactly how pf will choose the nat address though - that might be a problem.

**Comment by mekanix** [comment]
What I think would be good is to add like "-p 4" or "-p 6" to watch only for ipv4/ipv6. That way "v4/v6" from the start would be lost and if there's only one fib, then fib0 would be lost, leaving you only with "egress".  I will have to research it a bit, but what do you think about that? I mean, in that case every user could configure it the way they want.

**Comment by mekanix** [comment]
I added `-p` and documented it in man page. Is that sufficiently good?

**Comment by dfr** [comment]
I guess that would probably work for my setup where both default routes are on the same interface. I'm still not quite understanding the problem with putting the interface in 'egress' as well as <proto>egress. Having an interface in multiple groups seems to work well:
```
ifconfig lan0.42
lan0.42: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> metric 0 mtu 9000
        ...
	groups: vlan v4egress v6egress
```
I'm just suggesting to add egress as well as v4egress and v6egress to support simple setups without losing the ability to distinguish different v4 and v6 interfaces.

**Comment by dfr** [comment]
Anyway, for now, something like 'egress-monitor -p 4' will be fine for me and probably for many others.

**Comment by dfr** [comment]
When you get around to updating the port, I guess we need a way to specify flags for the egress-monitor command line as well.

**Comment by mekanix** [comment]
Updated port with https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=268117. The way to add options is to add `egress_monitor_flags="-p 4"` in rc.conf.
